### ISSUE TITLE
Code generator not producing correct Python types for all ECore Integer types

### ISSUE THREAD

**Issue by moltob** [aranega/pyecore#1]
Hi,

first of all: this is a great project. I was looking for something like this for quite a while and did not take on the effort to implement it myself. I am thrilled to see the level of features you have already working and would love to use this in my own projects.

When starting to play with this library I also tried the generator via genmycode and noticed that a few integer types are not properly translated, e.g. `EIntegerObject`:

    major = EAttribute(eType=EIntegerObject)
    minor = EAttribute(eType=EIntegerObject)

This generated code does not compile as the literally copied type name is not defined in the library as meta -meta type...

I am happy to update the generator via PR if you like, just let me know. If you're accepting PRs, I'd also fix a few other things like Python keyword collisions at some later point.

Would this work for you?

Best,
Mike

**Comment by aranega** [comment]
Hi Mike,

Thanks a lot for your encouragement! As you saw, the implementation is still rough on the edges and the issue you have is a good example of it. 
About this, I see two solutions:

1. modify the generator in order to map `EIntegerObject` to `EInteger` (as you propose),
1. create and add the `EIntegerObject` into PyEcore directly (in `ecore.py`).

To be honnest, I'm unable to say which one is the better. The "mapping" in the generator was here to quickly (and badly) managed some types from `XMLTypes.ecore` withtout embedding/loading the file. So I would tend to say that the second solution seems slightly better as it also introduces a new kind of semantic information (as the choice of `EIntegerObject` over `EInteger` or `EInt` have been made in the metamodel during modeling). What do you think about it?

Anyway, I totally accept PR, they are more than welcome. Also, I would be happy to get any PR you could propose.

Thanks again Mike!
Vince

**Comment by moltob** [comment]
Thank you for the friendly welcome! You're probably right to better add types directly to `ecore.py`. I'll look at it and make a suggestions via PR. Which branch do you suggest to submit PRs for?

**Comment by aranega** [comment]
If you could sumbit every PR to the `develop` branch, it would be perfect, as I need to check first how to properly manage hotfixes with 'gitflow' and how it will react with how 'bumpversion' is used in the project.

Once again, thanks Mike, that's so great to see people interested by this project and who contribute to it!

**Comment by aranega** [comment]
Again Mike, thanks a lot for your PR. I will make a release to bump from 0.1.4 to 0.1.5 probably today also on pypi (unless you have more PR to do ;) ). I will close the issue in the same time.
